---
name: Sample workflow

run-name: Sample workflow run

on:
  push:
    branch: [master]
  workflow_dispatch:

jobs:
  Sample_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show project files
        run: ls -r
